theme: minima
exclude: [README.md]

# TODO: zmenit skolsky rok podla potreby
title: Diplomový seminár DAV 2026/27

# TODO: zmenit podla semestra ZS/LS
header_pages:
  - index.md
  - Pravidlá_ZS.md 
  - Kontakt.md
  - Návod.md
  
